language:
  - cpp

os:
  - linux

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
# * http://stackoverflow.com/a/30925448/2288008
addons:
  apt:
    packages:
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

install:
  # Info about OS
  - uname -a

script:
  - echo "Hello"
